lines = [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "import anthropic\n",
    "import os\n",
    "from dotenv import load_dotenv\n",
    "from data_fetcher import fetch_and_store\n",
    "from analysis import compute_metrics\n",
    "\n",
    "load_dotenv('config.env')\n",
    "client = anthropic.Anthropic(api_key=os.getenv('ANTHROPIC_API_KEY'))\n",
    "\n",
    "def generate_narrative(ticker, metrics):\n",
    "    latest = metrics.iloc[-1]\n",
    "    prev = metrics.iloc[-2]\n",
    "    prompt = f'You are a CFO analyst. Write a concise 3-paragraph financial summary for {ticker} based on this data: Revenue ${latest[\"revenue\"]/1e9:.1f}B growing at {latest[\"revenue_growth\"]:.1f}% YoY. Gross margin {latest[\"gross_margin\"]:.1f}% (vs {prev[\"gross_margin\"]:.1f}% prior year). Operating margin {latest[\"operating_margin\"]:.1f}% (vs {prev[\"operating_margin\"]:.1f}% prior year). Net margin {latest[\"net_margin\"]:.1f}%. Be direct and analytical. No bullet points.'\n",
    "    message = client.messages.create(model='claude-sonnet-4-6', max_tokens=500, messages=[{'role': 'user', 'content': prompt}])\n",
    "    return message.content[0].text\n",
    "\n",
    "st.set_page_config(page_title='Company Financial Health Monitor', layout='wide')\n",
    "st.title('Company Financial Health Monitor')\n",
    "\n",
    "ticker = st.text_input('Enter a stock ticker', value='MSFT').upper()\n",
    "\n",
    "if st.button('Analyse'):\n",
    "    with st.spinner('Fetching data...'):\n",
    "        fetch_and_store(ticker)\n",
    "    metrics = compute_metrics(ticker)\n",
    "    st.markdown(f'**{ticker}** - 4-Year Financial Performance Summary')\n",
    "    st.divider()\n",
    "    latest = metrics.iloc[-1]\n",
    "    prev = metrics.iloc[-2]\n",
    "    col1, col2, col3, col4 = st.columns(4)\n",
    "    with col1:\n",
    "        st.metric('Revenue (Latest)', f'${latest[\"revenue\"]/1e9:.1f}B', delta=f'{latest[\"revenue_growth\"]:.1f}% YoY')\n",
    "    with col2:\n",
    "        st.metric('Gross Margin', f'{latest[\"gross_margin\"]:.1f}%', delta=f'{(latest[\"gross_margin\"]-prev[\"gross_margin\"]):.1f}pp')\n",
    "    with col3:\n",
    "        st.metric('Operating Margin', f'{latest[\"operating_margin\"]:.1f}%', delta=f'{(latest[\"operating_margin\"]-prev[\"operating_margin\"]):.1f}pp')\n",
    "    with col4:\n",
    "        st.metric('Net Margin', f'{latest[\"net_margin\"]:.1f}%', delta=f'{(latest[\"net_margin\"]-prev[\"net_margin\"]):.1f}pp')\n",
    "    st.divider()\n",
    "    col_left, col_right = st.columns(2)\n",
    "    with col_left:\n",
    "        st.subheader('Revenue Growth ($B)')\n",
    "        fig1 = px.bar(metrics, x='date', y='revenue', text=metrics['revenue'].apply(lambda x: f'${x/1e9:.0f}B'), color_discrete_sequence=['#0078D4'])\n",
    "        fig1.update_traces(textposition='outside')\n",
    "        fig1.update_layout(xaxis_title='Year', yaxis_title='Revenue ($)', showlegend=False, xaxis=dict(type='category'))\n",
    "        st.plotly_chart(fig1, use_container_width=True)\n",
    "    with col_right:\n",
    "        st.subheader('Margin Trends (%)')\n",
    "        fig2 = go.Figure()\n",
    "        fig2.add_trace(go.Scatter(x=metrics['date'], y=metrics['gross_margin'], mode='lines+markers', name='Gross Margin', line=dict(color='#0078D4', width=2)))\n",
    "        fig2.add_trace(go.Scatter(x=metrics['date'], y=metrics['operating_margin'], mode='lines+markers', name='Operating Margin', line=dict(color='#00B294', width=2)))\n",
    "        fig2.add_trace(go.Scatter(x=metrics['date'], y=metrics['net_margin'], mode='lines+markers', name='Net Margin', line=dict(color='#FFB900', width=2)))\n",
    "        fig2.update_layout(xaxis_title='Year', yaxis_title='Margin (%)', xaxis=dict(type='category'))\n",
    "        st.plotly_chart(fig2, use_container_width=True)\n",
    "    st.divider()\n",
    "    st.subheader('Full Metrics Table')\n",
    "    display = metrics[['date', 'revenue', 'gross_margin', 'operating_margin', 'net_margin', 'revenue_growth']].copy()\n",
    "    display['revenue'] = display['revenue'].apply(lambda x: f'${x/1e9:.1f}B')\n",
    "    display['gross_margin'] = display['gross_margin'].apply(lambda x: f'{x:.1f}%')\n",
    "    display['operating_margin'] = display['operating_margin'].apply(lambda x: f'{x:.1f}%')\n",
    "    display['net_margin'] = display['net_margin'].apply(lambda x: f'{x:.1f}%')\n",
    "    display['revenue_growth'] = display['revenue_growth'].apply(lambda x: f'{x:.1f}%' if pd.notna(x) else '-')\n",
    "    display.columns = ['Year', 'Revenue', 'Gross Margin', 'Operating Margin', 'Net Margin', 'Revenue Growth']\n",
    "    st.dataframe(display, use_container_width=True, hide_index=True)\n",
    "    st.divider()\n",
    "    st.subheader('AI Financial Narrative')\n",
    "    with st.spinner('Generating CFO summary...'):\n",
    "        narrative = generate_narrative(ticker, metrics)\n",
    "    st.write(narrative)\n",
]

with open('app.py', 'w', encoding='utf-8') as f:
    f.writelines(lines)

print('app.py created successfully')